### ISSUE TITLE
Installation bugs

### ISSUE THREAD

**Issue by Root3287** [samerton/NamelessMC#42] opened 2015-06-15 15:32 UTC
Hey Sam,
I did some bug testing and I found a few I think. I couldn't get past the installation because I kept on making a mistake. When I go back to the page the document had already expired. So I couldn't go back. Also for the outgoing email is that supposed to be valid or not I was thinking that not, because php mail function. Then register an admin there was an problem. There is one more problem with the infraction and or buycraft. If checked the setting page will go blank and press continued or submit the thing will just sit there. Any more Ill try to inform you thanks.

**Comment by Root3287** [comment] 2015-06-15 15:42
Sorry about the wrong title. Well it had something to do with installation

**Comment by samerton** [comment] 2015-06-15 15:42
Hi,

Can you edit inc/init.php and enable error reporting? That should result in errors appearing instead of a blank page.

As for the page being expired, nothing can be done about this, you'll have to refresh the page after clicking back.

**Comment by Root3287** [comment] 2015-06-15 15:43
Sure things

**Comment by Root3287** [comment] 2015-06-15 15:44
It usually come up with an error because I use Xampp

**Comment by Root3287** [comment] 2015-06-15 15:44
But still

**Comment by samerton** [comment] 2015-06-15 15:45
The package is set to disable all errors by default.

**Comment by Root3287** [comment] 2015-06-15 15:56
yea I see but no errors :\

**Comment by Root3287** [comment] 2015-06-15 15:58
Its only doesnt work when the link is /install/?step=settings_extra&c=true

**Comment by samerton** [comment] 2015-06-15 16:03
Can't reproduce this issue I'm afraid, and there's not much that can be done without any errors. Can you try clearing out your database, redownload the files and try again?

**Comment by Root3287** [comment] 2015-06-15 16:03
Sure thing

**Comment by Root3287** [comment] 2015-06-15 16:05
Ok now it work

**Comment by samerton** [comment] 2015-06-15 16:09
As for the question "Also for the outgoing email is that supposed to be valid or not I was thinking that not, because php mail function", the email will need to be valid. As you say, it uses the PHP mail function however this will change in a future update.

I'll close this for now, glad you've got it working.

**Closed as completed by samerton** 2015-06-15 16:09 UTC

**Comment by Root3287** [comment] 2015-06-15 16:11
But how about the account for the admin?

**Comment by samerton** [comment] 2015-06-15 16:45
Fixed in [latest commit](https://github.com/samerton/NamelessMC/commit/bafc759c33916f7f5213c6b64912191fe92ea3dc). It appeared to be an issue in general whilst creating accounts.
