### ISSUE TITLE
Error 404 on website

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#29] opened 2015-05-26 19:34 UTC
http://prntscr.com/79pprt

Installed properly, but i get an error 404 every time i go to my website

**Comment by samerton** [comment] 2015-05-26 19:36
Can you try moving the files out of the NamelessMC-master folder into the public_html folder? The package needs to be in the root directory to work properly.

**Comment by Kyle1264x** [comment] 2015-05-26 19:38
I have my forwarding set for it to read the public_html

**Comment by Kyle1264x** [comment] 2015-05-26 19:39
http://prntscr.com/79psyd
Even with that i get now:"
403 Forbidden

nginx/1.6.2

**Comment by samerton** [comment] 2015-05-26 21:03
Which files are present in the root directory?

**Comment by Kyle1264x** [comment] 2015-05-26 21:08
All of the files in the most recent download 

Kyle

**Comment by samerton** [comment] 2015-05-26 21:53
Is your web server correctly configured to allow .htaccess files and mod_rewrite?

**Comment by Kyle1264x** [comment] 2015-05-26 22:04
Yup. Both are allowed 

Kyle

**Comment by samerton** [comment] 2015-05-26 22:42
It looks to me like a server configuration issue; can you try installing something else (such as Wordpress) just to see if that works correctly?

**Comment by Kyle1264x** [comment] 2015-05-26 22:52
My other website works fine. I just changed the path of the files to show these and not them 

Kyle

**Comment by samerton** [comment] 2015-05-26 23:04
Can you try navigating to a file directly, for example _url_/pages/index.php

If this returns an error I'm afraid it must be a server configuration issue.

**Comment by Kyle1264x** [comment] 2015-05-27 00:11
I'll try that, Also to allow ht access for my nginx server

**Comment by Kyle1264x** [comment] 2015-05-27 00:36
http://prntscr.com/79tdat

**Comment by Kyle1264x** [comment] 2015-05-27 00:39
Also, my web server is under /var/www/apexnetwork.org

**Comment by Kyle1264x** [comment] 2015-05-27 02:09
The install.php brings up a blank page

**Comment by Kyle1264x** [comment] 2015-05-27 02:15
http://apexnetwork.org/pages/install.php using that

**Comment by samerton** [comment] 2015-05-27 09:41
This shows that the files are in the correct location, however in order to use the package you'll need to navigate to http://apexnetwork.org/install 
The issue here is that it returns a 404. It appears you've switched from nginx to Apache.

Try using the following commands in SSH:
a2enmod rewrite
service apache2 restart

If they don't work, try [this guide](https://help.ubuntu.com/community/EnablingUseOfApacheHtaccessFiles)

**Comment by Kyle1264x** [comment] 2015-05-27 11:07
Says 
Module rewrite is already enabled 

Also already configured the ht access 

Kyle

**Comment by samerton** [comment] 2015-05-27 11:12
I'm afraid I don't know too much about Ubuntu/Apache. Have you tried restarting Apache?

**Comment by samerton** [comment] 2015-05-27 11:18
Looking at your post in the Spigot thread, it appears you're missing double quotes around /var/www/apexnetwork.org/ in the code you pasted. It should look like [this](https://gist.githubusercontent.com/samerton/aaa63a0ada0e5e415146/raw/775b17e4ce864e9afc64744cd41bc22781844dd2/gistfile1.txt)

**Comment by Kyle1264x** [comment] 2015-05-27 11:18
Many many times. Do you use nginx?

Kyle

**Comment by samerton** [comment] 2015-05-27 11:29
I haven't used nginx before, I'd have to look into how that rewrites URLs as .htaccess files won't work in nginx.

**Comment by Kyle1264x** [comment] 2015-05-27 11:56
Just did what you said:
http://prntscr.com/79y569
http://paste.ee/r/wJp2N

The first one is my sites-available picture, then the code for the apexnetwork.org

**Comment by Kyle1264x** [comment] 2015-05-27 11:56
http://prntscr.com/79y629

Here is a picture of the directory where the files are located

**Comment by samerton** [comment] 2015-05-27 12:06
There should be a file named ".htaccess" in the root directory, alongside "404.php", "changelog.txt" and "index.php". 

It doesn't appear to be present, please create one with [this code](https://github.com/samerton/NamelessMC/blob/master/.htaccess)

**Comment by Kyle1264x** [comment] 2015-05-27 12:12
That fixed it, Thanks. Also can you add support for the http://www.spigotmc.org/resources/litebans.3715/ plugin, for the web interface?

**Comment by Kyle1264x** [comment] 2015-05-27 12:18
New bug:

Getting stuck on the http://apexnetwork.org/install/?step=account page

http://prntscr.com/79ydvc

**Comment by samerton** [comment] 2015-05-27 12:22
Can you add [this code](https://gist.githubusercontent.com/samerton/4909c7694ff435280765/raw/e2d5e7e7ea131e271ca28975def2dc082230cbaf/Error%20Reporting) to the top of pages/install.php, underneath the opening <?php tag

This should result in an error appearing instead of an empty white page.

**Comment by Kyle1264x** [comment] 2015-05-27 12:29
Added it, Also where do i find the API key for buycraft

**Comment by samerton** [comment] 2015-05-27 12:34
The API key is the secret code which you put into your Buycraft configuration file on your Minecraft server, or by visiting the [Buycraft dashboard](https://server.buycraft.net/servers)

**Comment by Kyle1264x** [comment] 2015-05-27 12:35
Fatal error: Call to undefined function curl_init() in /var/www/html/inc/integration/uuid.php on line 102

Theres the error causing the blank screen

**Comment by samerton** [comment] 2015-05-27 12:36
Ensure cURL is installed on your web server.

sudo apt-get install php5-curl
sudo service apache2 restart

**Comment by Kyle1264x** [comment] 2015-05-27 12:40
Now it says after restarting everything from the beginning,
Right after the admin account information

There was a problem performing that action.

**Comment by samerton** [comment] 2015-05-27 12:41
Please clear out your database and then reinstall

**Comment by Kyle1264x** [comment] 2015-05-27 12:45
white screen at
http://apexnetwork.org/admin/?from=install
right after i add the admin details

**Comment by samerton** [comment] 2015-05-27 12:51
Can you edit inc/init.php, and enable error reporting.

(Find the line "// Uncomment the following 3 lines to enable error reporting, and comment the 4th and 5th lines" and follow the instructions)

**Comment by Kyle1264x** [comment] 2015-05-27 12:57
Fatal error: Call to a member function results() on a non-object in /var/www/html/inc/classes/Queries.php on line 12

**Comment by samerton** [comment] 2015-05-27 12:58
Did you run the installer from the start after clearing the database?

**Comment by Kyle1264x** [comment] 2015-05-27 12:59
Yup, would you like me to do it again?

**Comment by Kyle1264x** [comment] 2015-05-27 13:03
Just deleted the databases, and tried starting over, same error
Fatal error: Call to a member function results() on a non-object in /var/www/html/inc/classes/Queries.php on line 12

**Comment by Kyle1264x** [comment] 2015-05-27 13:14
Just retried it all again, Same problem. Stuck on that page

http://prntscr.com/79yz68

**Comment by samerton** [comment] 2015-05-27 13:16
Can you manually delete pages/install.php? Doubt this is the cause of the error, however it seems to still be present.

**Comment by Kyle1264x** [comment] 2015-05-27 13:17
Even after refreshing the page still stuck there

**Comment by Kyle1264x** [comment] 2015-05-27 13:18
Even when loading the site now, from a new tab, its just blank and white

**Comment by samerton** [comment] 2015-05-27 13:21
Just tried installing myself, I can reproduce the issue. Investigating now.

**Comment by Kyle1264x** [comment] 2015-05-27 13:22
Would you like me to re flush my databases? and get a clean install prepared, or will you push an update

**Comment by samerton** [comment] 2015-05-27 13:23
Found the cause of the issue, pushing an update now.

**Comment by Kyle1264x** [comment] 2015-05-27 13:25
Sounds good

**Comment by samerton** [comment] 2015-05-27 13:33
Fixed in the new [version 0.3.2](https://github.com/samerton/NamelessMC/releases/tag/v0.3.2).

Please clear out the database, redownload and reinstall.

**Comment by Kyle1264x** [comment] 2015-05-27 13:33
Will do now

**Comment by Kyle1264x** [comment] 2015-05-27 13:34
Also, the .htaccess doesnt download in the file for me. I need to remake it every time

**Comment by samerton** [comment] 2015-05-27 13:35
Which OS do you use on your main computer?

**Comment by Kyle1264x** [comment] 2015-05-27 13:35
Right now im on my Mac, but on my main computer windows 8.1. Both dont download the .htaccess

**Comment by samerton** [comment] 2015-05-27 13:38
I believe .htaccess files are hidden by default in a number of different OSs, so you'll need to make them visible.

**Comment by Kyle1264x** [comment] 2015-05-27 13:41
Gotcha, Just finished the installation, logged into the admin panel. But now that i go to my website, apexnetwork.org it shows the installation again

**Comment by samerton** [comment] 2015-05-27 13:42
Please delete the pages/install.php file manually, it seems the installer was unable to do so itself, possibly due to permissions.

**Comment by Kyle1264x** [comment] 2015-05-27 13:44
That worked, Thanks.

Also do you mind adding support for litebans? I can get you the needed files for it.  It has a web interface itself

**Comment by samerton** [comment] 2015-05-27 13:44
Sure, all I'd need is the database structure and I'll see what I can do.

**Comment by Kyle1264x** [comment] 2015-05-27 13:44
How can i get that to you?

**Comment by samerton** [comment] 2015-05-27 13:45
Just found the plugin, I'll buy it myself and take a look.

**Comment by Kyle1264x** [comment] 2015-05-27 13:46
I dont mind sending you the money for it. Youve been a tremendous help

**Comment by samerton** [comment] 2015-05-27 13:47
Don't worry about it, glad to help.

**Comment by Kyle1264x** [comment] 2015-05-27 13:48
Sounds good man, Really appreciate all the work.

**Comment by samerton** [comment] 2015-05-27 13:50
I'll close this issue, and make a start on LiteBans.

**Closed as completed by samerton** 2015-05-27 13:50 UTC
Labels: bug
