### ISSUE TITLE
Message notification

### ISSUE THREAD

**Issue by zRiaz** [samerton/NamelessMC#46] opened 2015-06-27 22:46 UTC
I received a message, and opened it & replied to it..
But the "!" notification is still on there. (I did double check too, no new message).

**Comment by samerton** [comment] 2015-06-27 23:10
Can't reproduce any issues on my end. Can you check the 'private_messages_users' table and see if the value for 'read' is set as 0 or 1, for your user ID and PM ID?

**Comment by zRiaz** [comment] 2015-06-27 23:39
Uh too advanced for me.. lol
But since I replied to the message it said like at the participaters thing "myname,hisname,myname"
And the message I replied too (with my reply) reappeared in my inbox as a message to myself.. And when I deleted it the notification dissapeared.
I think it sent myself a message since I was participating in a convo with him and it sent it to myself too? And was like unreadable etc.

**Comment by samerton** [comment] 2015-06-27 23:59
Interesting, I'll look into it.

**Comment by CoderFetch** [comment] 2015-07-01 13:41
About the participants thing, I think I might have found what is causing that.

***_From messaging.php, lines 208 - 213**_*

``` php
                                        if($user_id){
                                            $queries->create("private_messages_users", array(
                                                'pm_id' => $last_id,
                                                'user_id' => $user_id
                                            ));
                                        }
```

You don't seem to be checking if the user was _already added as a participant_. You just create a new entry anyway.

**Comment by samerton** [comment] 2015-07-01 14:23
Thanks, fixed in the latest commit.

**Closed as completed** 2015-07-01 14:23 UTC
