### ISSUE TITLE
Random titles are going missing

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#38] opened 2015-06-04 03:11 UTC
It seems like random titles are going missing on forum posts.

**Comment by Kyle1264x** [comment] 2015-06-04 03:15
Or people are inputting them without titles, making them unaccessable unless changed in the MySQL.

**Comment by samerton** [comment] 2015-06-04 10:13
Don't know what could be causing this, can't reproduce on my side. Titles are checked so they must be a minimum length of 2 characters before submitting a post.

**Comment by Kyle1264x** [comment] 2015-06-04 10:31
Seems like it's only happening after adding the code for the recent posts 

Kyle

**Comment by samerton** [comment] 2015-06-04 10:51
The recent posts fix shouldn't affect post titles as it will only reorder a list of posts. I've noticed a number of other sites with the same issue, however the title appeared to fix itself after a number of reloads.
Is the MySQL database 'topic_title' entry in the 'topics' table empty?

**Comment by Kyle1264x** [comment] 2015-06-04 11:06
Yeah. And if I want to even see the post I need to go in and edit it. 

Kyle

**Comment by samerton** [comment] 2015-06-04 11:09
Unfortunately I have no idea as to what could be happening. Next time it happens, is there any chance you could ask the user what happened when they made their post?

**Comment by Kyle1264x** [comment] 2015-06-04 11:11
Sure 
Kyle

**Comment by dwilson390** [comment] 2015-06-04 15:03
Just a note, I have experienced this issue too, it seem to happen after editing the post title however when I changed title in MySQL to 'Undefined' then changed it on the front end, nothing went wrong.

**Comment by dwilson390** [comment] 2015-06-05 21:08
This appears to be being cause by editing a reply, not actually editing the title.

**Comment by samerton** [comment] 2015-06-05 23:13
Thanks, fixed in latest commit.

**Closed as completed** 2015-06-05 23:12 UTC
