### ISSUE TITLE
Server Query API Bug

### ISSUE THREAD

**Issue by imperiagroup** [samerton/NamelessMC#58] opened 2015-08-01 13:50 UTC
When external query is not selected, the server appears online and the player list works in the Play page.

However, the main server on the homepage banner appears offline.

When enabling external query, the opposite happens, the servers on the play list appear offline and the main server on the banner is online.

**Comment by samerton** [comment] 2015-08-01 15:27
I can't reproduce any issues, I'll look into it though.

**Comment by RawrUniversal** [comment] 2015-08-01 23:03
Another bug, When a player is online on the server it doesnt show they are online on their profile.

**Comment by imperiagroup** [comment] 2015-08-01 23:05
I can confirm that RAWR's bug happens on my website as well.

On Saturday, August 1, 2015, Me_Goes_RAWR notifications@github.com wrote:

> Another bug, When a player is online on the server it doesnt show they are
> online on their profile.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samerton/NamelessMC/issues/58#issuecomment-126960679.

## 

Best regards,

Anthony

**Comment by samerton** [comment] 2015-08-02 08:56
@megoesrawr @Motorbond Are you using the external query?

**Comment by imperiagroup** [comment] 2015-08-03 03:45
I've tried both, and they just have the opposite errors.

On Sunday, August 2, 2015, samerton notifications@github.com wrote:

> @megoesrawr https://github.com/megoesrawr @Motorbond
> https://github.com/Motorbond Are you using the external query?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samerton/NamelessMC/issues/58#issuecomment-127000228.

## 

Best regards,

Anthony

**Comment by RawrUniversal** [comment] 2015-08-04 12:47
I'm using the normal query.

**Comment by samerton** [comment] 2015-09-05 22:23
The latest [version 1.0](https://github.com/NamelessMC/Nameless) code includes the ability to check internal query errors in the AdminCP's Minecraft tab; these could be used to diagnose your issues.

**Comment by samerton** [comment] 2016-01-01 13:30
I'm going to close this issue as it should have been fixed in [this 1.0.0 commit](https://github.com/NamelessMC/Nameless/commit/d76cfde0029649bc76fdb3eacb6b8e98885ba48f).

**Closed as completed by samerton** 2016-01-01 13:30 UTC
